version: "3.9"

services:
  backend:
    build: .
    container_name: napasa_main_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      DB_HOST: napasa_main_postgres
      DB_PORT: 5432
      DB_NAME: napasa_main_backend
      DB_USER: shedrack
      DB_PASSWORD: SHEDRACKs.677
      JWT_SECRET: SHEDRACKs.677
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - napasa_main_postgres
    networks:
      - napasa_ai_network
    command: node server.js

  napasa_main_postgres:
    image: postgres:16
    container_name: napasa_main_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shedrack
      POSTGRES_PASSWORD: SHEDRACKs.677
      POSTGRES_DB: napasa_main_backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - napasa_ai_network

volumes:
  pgdata:

networks:
  napasa_ai_network:
    external: true
    name: napasa-ai-backend_napasa_ai_network
